### ISSUE TITLE
Problèmes au niveau des scores

### ISSUE THREAD

**Issue by brekezek** [droduit/sharp-ch#40]
En me basant sur le questionnaire de Pascal Cusin, je constate quelques incohérences, oar ordre d'importance:
- [x] ENV 11 q 6: pas de score alors qu'il a fourni des réponses

- [x] EC11 q4: On entre 0 par défaut, ce qui est problématique étant donné que c'est pratiquement impossible pour les agris qu'on rencontre. Il faudrait passer à NA par défaut

- [x] EC05 q1: La moyenne devrait d'abord se faire par production avant de faire la moyenne des productions.

**Comment by droduit** [comment]
**ENV11 q6**
Le calcul du score de la question 6 et 7 est ensemble. Le score dépend des deux questions, et ne peut donc pas exister sans les deux réponses. Donc le score n'est jamais donné pour la question 6, il sera vide dans tous les cas, car je calcul un seul score pour les deux que je reporte dans la question 7. Malheureusement, il y a quand meme un problème ici car la question 7 n'a pas de score non plus.

**Comment by droduit** [comment]
**EC_11 q4**
J'ai fait un fix "temporaire" qui consiste à repasser le type du champ en "text" au lieu de "integer", et dans les scores, si la réponse est un texte, score pas pris en compte, sinon je calcul en fonction de l'echelle donnée pour les integer. Ca me permet d'afficher le "N/A" dans le champ de texte. Par contre ce n'est pas possible en HTML d'afficher autre chose qu'un entier dans un champ de type entier, et la valeur 0 est le placeholder de base, mais si le champ n'est pas rempli, c'est en fait un champ vide et pas la valeur 0 qui est enregistrée (je crois, j'ai un doute soudainement). Aussi, pour ce champ, je dois convertir toutes les réponses textes en numérique. Une fois cela fait, je repasserai le champ en type entier, et je verrai quelle solution je peux trouver pour ce N/A plutot que le placeholder 0 (peut etre un champ de type texte avec un pattern qui n'accepte que les nombres entiers pour avoir le placeholder qu'on veut et ne pas permettre autre chose que des chiffres).

**Comment by droduit** [comment]
**EC_05 q1**
Tu as raison. J'ai modifié.
